// Automatically generated rewards mapping
export interface RewardOffer {
  bankName: string;
  product: string;
  employmentType: string;
  minLoanAmount: number;
  maxLoanAmount: number;
  pointsValue: string;
  reward1: string;
  reward2: string;
  pfWaiver: string;
}

export const REWARDS_DATA: RewardOffer[] = [
  {
    "bankName": "HDFC",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "HAND STEAMER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "HDFC",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "AIR FRYER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "HDFC",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "HDFC",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "HDFC",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "SMART PHONE",
    "reward2": "42\" LED TV",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "HDFC",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "HDFC",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 15",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "HDFC",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "HAND STEAMER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "HDFC",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "AIR FRYER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "HDFC",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "HDFC",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "TOP LOAD SEMI AUTOMATIC WASHING MACHINE",
    "reward2": "32\" SMART LED TV",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "HDFC",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "HDFC",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "HDFC",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 15",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "HDFC",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "AIR FRYER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "HDFC",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "HAND STEAMER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "HDFC",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "HDFC",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "TOP LOAD SEMI AUTOMATIC WASHING MACHINE",
    "reward2": "32\" SMART LED TV",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "HDFC",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "HDFC",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "HDFC",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 16",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "STATE BANK OF INDIA",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "AIR FRYER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "STATE BANK OF INDIA",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "HAND STEAMER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "STATE BANK OF INDIA",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "STATE BANK OF INDIA",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "TOP LOAD SEMI AUTOMATIC WASHING MACHINE",
    "reward2": "32\" SMART LED TV",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "STATE BANK OF INDIA",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "STATE BANK OF INDIA",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "STATE BANK OF INDIA",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 16",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "STATE BANK OF INDIA",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "HAND STEAMER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "STATE BANK OF INDIA",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "AIR FRYER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "STATE BANK OF INDIA",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "STATE BANK OF INDIA",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "STATE BANK OF INDIA",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "SMART PHONE",
    "reward2": "42\" LED TV",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "STATE BANK OF INDIA",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "STATE BANK OF INDIA",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 15",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "STATE BANK OF INDIA",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "HAND STEAMER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "STATE BANK OF INDIA",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "AIR FRYER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "STATE BANK OF INDIA",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "STATE BANK OF INDIA",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "TOP LOAD SEMI AUTOMATIC WASHING MACHINE",
    "reward2": "32\" SMART LED TV",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "STATE BANK OF INDIA",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "STATE BANK OF INDIA",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "STATE BANK OF INDIA",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 15",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "BANK OF BARODA",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "AIR FRYER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BANK OF BARODA",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "HAND STEAMER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BANK OF BARODA",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BANK OF BARODA",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "TOP LOAD SEMI AUTOMATIC WASHING MACHINE",
    "reward2": "32\" SMART LED TV",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BANK OF BARODA",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "BANK OF BARODA",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "BANK OF BARODA",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 16",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "BANK OF BARODA",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "AIR FRYER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BANK OF BARODA",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "HAND STEAMER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BANK OF BARODA",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BANK OF BARODA",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "TOP LOAD SEMI AUTOMATIC WASHING MACHINE",
    "reward2": "32\" SMART LED TV",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BANK OF BARODA",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "BANK OF BARODA",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "BANK OF BARODA",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 16",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "BANK OF BARODA",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "HAND STEAMER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BANK OF BARODA",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "AIR FRYER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BANK OF BARODA",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BANK OF BARODA",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BANK OF BARODA",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "SMART PHONE",
    "reward2": "42\" LED TV",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "BANK OF BARODA",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "BANK OF BARODA",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 15",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "L&T FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "HAND STEAMER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "L&T FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "AIR FRYER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "L&T FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "L&T FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "TOP LOAD SEMI AUTOMATIC WASHING MACHINE",
    "reward2": "32\" SMART LED TV",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "L&T FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "L&T FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "L&T FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 15",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "L&T FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "AIR FRYER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "L&T FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "HAND STEAMER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "L&T FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "L&T FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "TOP LOAD SEMI AUTOMATIC WASHING MACHINE",
    "reward2": "32\" SMART LED TV",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "L&T FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "L&T FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "L&T FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 16",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "L&T FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "AIR FRYER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "L&T FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "HAND STEAMER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "L&T FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "L&T FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "TOP LOAD SEMI AUTOMATIC WASHING MACHINE",
    "reward2": "32\" SMART LED TV",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "L&T FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "L&T FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "L&T FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 16",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "ICICI BANK",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "HAND STEAMER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "ICICI BANK",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "AIR FRYER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "ICICI BANK",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "ICICI BANK",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "ICICI BANK",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "SMART PHONE",
    "reward2": "42\" LED TV",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "ICICI BANK",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "ICICI BANK",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 15",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "ICICI BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "HAND STEAMER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "ICICI BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "AIR FRYER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "ICICI BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "ICICI BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "TOP LOAD SEMI AUTOMATIC WASHING MACHINE",
    "reward2": "32\" SMART LED TV",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "ICICI BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "ICICI BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "ICICI BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 15",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "ICICI BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "AIR FRYER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "ICICI BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "HAND STEAMER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "ICICI BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "ICICI BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "TOP LOAD SEMI AUTOMATIC WASHING MACHINE",
    "reward2": "32\" SMART LED TV",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "ICICI BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "ICICI BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "ICICI BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 16",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "BANDHAN BANK",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "AIR FRYER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BANDHAN BANK",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "HAND STEAMER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BANDHAN BANK",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BANDHAN BANK",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "TOP LOAD SEMI AUTOMATIC WASHING MACHINE",
    "reward2": "32\" SMART LED TV",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BANDHAN BANK",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "BANDHAN BANK",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "BANDHAN BANK",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 16",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "BANDHAN BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "HAND STEAMER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BANDHAN BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "AIR FRYER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BANDHAN BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BANDHAN BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BANDHAN BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "SMART PHONE",
    "reward2": "42\" LED TV",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "BANDHAN BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "BANDHAN BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 15",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "BANDHAN BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "HAND STEAMER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BANDHAN BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "AIR FRYER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BANDHAN BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BANDHAN BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "TOP LOAD SEMI AUTOMATIC WASHING MACHINE",
    "reward2": "32\" SMART LED TV",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BANDHAN BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "BANDHAN BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "BANDHAN BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 15",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "ADITYA BIRLA FINANCE LIMITED",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "AIR FRYER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "ADITYA BIRLA FINANCE LIMITED",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "HAND STEAMER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "ADITYA BIRLA FINANCE LIMITED",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "ADITYA BIRLA FINANCE LIMITED",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "TOP LOAD SEMI AUTOMATIC WASHING MACHINE",
    "reward2": "32\" SMART LED TV",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "ADITYA BIRLA FINANCE LIMITED",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "ADITYA BIRLA FINANCE LIMITED",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "ADITYA BIRLA FINANCE LIMITED",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 16",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "ADITYA BIRLA FINANCE LIMITED",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "AIR FRYER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "ADITYA BIRLA FINANCE LIMITED",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "HAND STEAMER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "ADITYA BIRLA FINANCE LIMITED",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "ADITYA BIRLA FINANCE LIMITED",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "TOP LOAD SEMI AUTOMATIC WASHING MACHINE",
    "reward2": "32\" SMART LED TV",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "ADITYA BIRLA FINANCE LIMITED",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "ADITYA BIRLA FINANCE LIMITED",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "ADITYA BIRLA FINANCE LIMITED",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 16",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "ADITYA BIRLA FINANCE LIMITED",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "HAND STEAMER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "ADITYA BIRLA FINANCE LIMITED",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "AIR FRYER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "ADITYA BIRLA FINANCE LIMITED",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "ADITYA BIRLA FINANCE LIMITED",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "ADITYA BIRLA FINANCE LIMITED",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "SMART PHONE",
    "reward2": "42\" LED TV",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "ADITYA BIRLA FINANCE LIMITED",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "ADITYA BIRLA FINANCE LIMITED",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 15",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "BAJAJ FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "HAND STEAMER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BAJAJ FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "AIR FRYER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BAJAJ FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BAJAJ FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "TOP LOAD SEMI AUTOMATIC WASHING MACHINE",
    "reward2": "32\" SMART LED TV",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BAJAJ FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "BAJAJ FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "BAJAJ FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 15",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "BAJAJ FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "AIR FRYER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BAJAJ FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "HAND STEAMER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BAJAJ FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BAJAJ FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "TOP LOAD SEMI AUTOMATIC WASHING MACHINE",
    "reward2": "32\" SMART LED TV",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BAJAJ FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "BAJAJ FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "BAJAJ FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 16",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "BAJAJ FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "AIR FRYER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BAJAJ FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "HAND STEAMER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BAJAJ FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BAJAJ FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "TOP LOAD SEMI AUTOMATIC WASHING MACHINE",
    "reward2": "32\" SMART LED TV",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "BAJAJ FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "BAJAJ FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "BAJAJ FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 16",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "YES BANK",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "HAND STEAMER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "YES BANK",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "AIR FRYER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "YES BANK",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "YES BANK",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "YES BANK",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "SMART PHONE",
    "reward2": "42\" LED TV",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "YES BANK",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "YES BANK",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 15",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "YES BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "HAND STEAMER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "YES BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "AIR FRYER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "YES BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "YES BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "TOP LOAD SEMI AUTOMATIC WASHING MACHINE",
    "reward2": "32\" SMART LED TV",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "YES BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "YES BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "YES BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 15",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "YES BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "AIR FRYER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "YES BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "HAND STEAMER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "YES BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "YES BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "TOP LOAD SEMI AUTOMATIC WASHING MACHINE",
    "reward2": "32\" SMART LED TV",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "YES BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "YES BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "YES BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 16",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "JIO FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "AIR FRYER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "JIO FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "HAND STEAMER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "JIO FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "JIO FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "TOP LOAD SEMI AUTOMATIC WASHING MACHINE",
    "reward2": "32\" SMART LED TV",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "JIO FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "JIO FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "JIO FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 16",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "JIO FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "HAND STEAMER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "JIO FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "AIR FRYER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "JIO FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "JIO FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "JIO FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "SMART PHONE",
    "reward2": "42\" LED TV",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "JIO FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "JIO FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 15",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "JIO FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "HAND STEAMER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "JIO FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "AIR FRYER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "JIO FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "JIO FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "TOP LOAD SEMI AUTOMATIC WASHING MACHINE",
    "reward2": "32\" SMART LED TV",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "JIO FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "JIO FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "JIO FINANCE",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 15",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "IDBI BANK",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "AIR FRYER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "IDBI BANK",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "HAND STEAMER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "IDBI BANK",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "IDBI BANK",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "TOP LOAD SEMI AUTOMATIC WASHING MACHINE",
    "reward2": "32\" SMART LED TV",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "IDBI BANK",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "IDBI BANK",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "IDBI BANK",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 16",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "IDBI BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "AIR FRYER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "IDBI BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "HAND STEAMER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "IDBI BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "IDBI BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "TOP LOAD SEMI AUTOMATIC WASHING MACHINE",
    "reward2": "32\" SMART LED TV",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "IDBI BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "IDBI BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "IDBI BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 16",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "IDBI BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "HAND STEAMER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "IDBI BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "AIR FRYER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "IDBI BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "IDBI BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "IDBI BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "SMART PHONE",
    "reward2": "42\" LED TV",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "IDBI BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "IDBI BANK",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 15",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "TATA CAPITAL",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "HAND STEAMER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "TATA CAPITAL",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "AIR FRYER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "TATA CAPITAL",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "TATA CAPITAL",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "TOP LOAD SEMI AUTOMATIC WASHING MACHINE",
    "reward2": "32\" SMART LED TV",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "TATA CAPITAL",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "TATA CAPITAL",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "TATA CAPITAL",
    "product": "HOME LOAN",
    "employmentType": "SALARIED",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 15",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "TATA CAPITAL",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "AIR FRYER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "TATA CAPITAL",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "HAND STEAMER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "TATA CAPITAL",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "TATA CAPITAL",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "TOP LOAD SEMI AUTOMATIC WASHING MACHINE",
    "reward2": "32\" SMART LED TV",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "TATA CAPITAL",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "TATA CAPITAL",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "TATA CAPITAL",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED PROFESSIONAL",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 16",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "TATA CAPITAL",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 2000000,
    "maxLoanAmount": 3000000,
    "pointsValue": "3000-4000",
    "reward1": "MIXER SET",
    "reward2": "AIR FRYER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "TATA CAPITAL",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 3000001,
    "maxLoanAmount": 4000000,
    "pointsValue": "5000-6000",
    "reward1": "HAND STEAMER",
    "reward2": "MICROWAVE OVEN",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "TATA CAPITAL",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 4000001,
    "maxLoanAmount": 5000000,
    "pointsValue": "7000-8000",
    "reward1": "32\" LED TV",
    "reward2": "VACCUM CLEANER",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "TATA CAPITAL",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 5000001,
    "maxLoanAmount": 7500000,
    "pointsValue": "10000-12000",
    "reward1": "TOP LOAD SEMI AUTOMATIC WASHING MACHINE",
    "reward2": "32\" SMART LED TV",
    "pfWaiver": "50% PF WAIVER"
  },
  {
    "bankName": "TATA CAPITAL",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 7500001,
    "maxLoanAmount": 10000000,
    "pointsValue": "14000-17000",
    "reward1": "REFRIDGERATOR",
    "reward2": "TOP LOAD FULLY AUTOMATIC WASHING MACHINE",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "TATA CAPITAL",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 10000001,
    "maxLoanAmount": 20000000,
    "pointsValue": "18000-22000",
    "reward1": "SMART PHONE",
    "reward2": "LAPTOP",
    "pfWaiver": "100% PF WAIVER"
  },
  {
    "bankName": "TATA CAPITAL",
    "product": "HOME LOAN",
    "employmentType": "SELF EMPLOYEED NON PROFESSIONAL",
    "minLoanAmount": 20000001,
    "maxLoanAmount": Infinity,
    "pointsValue": "30000-60000",
    "reward1": "AIR CONDITIONER",
    "reward2": "iPHONE 16",
    "pfWaiver": "100% PF WAIVER"
  }
];

/**
 * Returns the matching reward offer for a given configuration.
 */
export function getRewardOffer(
  bankName: string,
  product: string,
  employmentType: string,
  loanAmount: number
): RewardOffer | null {
  // Normalize inputs
  const normBank = bankName.toUpperCase().trim();
  const normProduct = product.toUpperCase().trim();
  
  // Convert standard employment types to match the raw data format
  // Example: SALARIED -> SALARIED, SELF_EMPLOYED -> SELF EMPLOYEED NON PROFESSIONAL, PROFESSIONAL -> SELF EMPLOYEED PROFESSIONAL
  let normEmployment = employmentType.toUpperCase().trim();
  if (normEmployment === 'SELF_EMPLOYED') {
      normEmployment = 'SELF EMPLOYEED NON PROFESSIONAL'; // Typo from raw data 'EMPLOYEED'
  } else if (normEmployment === 'PROFESSIONAL' || normEmployment === 'SELF_EMPLOYED_PROFESSIONAL') {
      normEmployment = 'SELF EMPLOYEED PROFESSIONAL';
  } else if (normEmployment === 'SELF EMPLOYED NON PROFESSIONAL') {
      normEmployment = 'SELF EMPLOYEED NON PROFESSIONAL';
  } else if (normEmployment === 'SELF EMPLOYED PROFESSIONAL') {
      normEmployment = 'SELF EMPLOYEED PROFESSIONAL';
  }
  
  // Find match
  const match = REWARDS_DATA.find(offer => {
      // Relaxed bank matching (e.g. HDFC Bank -> HDFC)
      const bankMatch = normBank.includes(offer.bankName) || offer.bankName.includes(normBank);
      // Product matching
      const productMatch = offer.product === normProduct || normProduct.includes('HOME LOAN'); 
      // Employment match
      const empMatch = offer.employmentType === normEmployment;
      // Loan amount match
      const amountMatch = loanAmount >= offer.minLoanAmount && loanAmount <= offer.maxLoanAmount;
      
      return bankMatch && productMatch && empMatch && amountMatch;
  });
  
  return match || null;
}
